name: Build
on: [push, pull_request]
jobs:
  unix:
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-15]
        include:
          - runner: macos-15
            artifact: "*.dylib"
    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v4
      - run: cmake -DCMAKE_BUILD_TYPE=Release -G Ninja
      - run: ninja
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.runner}} Artifacts
          path: ${{matrix.artifact}}

  windows:
    strategy:
      fail-fast: false
      matrix:
        arch: [ Win32, x64, ARM64 ]
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - run: cmake -G "Visual Studio 17 2022" -A ${{matrix.arch}}
      - run: msbuild fabric_installer_native_lib.sln /property:Configuration=Release
      - uses: actions/upload-artifact@v4
        with:
          name: Windows (${{matrix.arch}}) Artifacts
          path: "Release/*"