name: Release
on: [workflow_dispatch] # Manual trigger
jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        arch: [ Win32, x64, ARM, ARM64 ]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.2
      - run: cmake -G "Visual Studio 16 2019" -A ${{matrix.arch}}
      - run: msbuild fabric_installer_native_lib.sln /property:Configuration=Release
      - run: gradle makeJar publish --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          INPUT: "Release/fabric_installer_native_lib.dll"
          NAME: "windows-${{ matrix.arch }}"
          FILENAME: "windows-${{ matrix.arch }}.dll"

  unix:
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-11.0, ubuntu-20.04]
        include:
          - runner: macos-11.0
            ext: dylib
            arch: x86_64_arm64
            name: macos
          - runner: ubuntu-20.04
            ext: so
            arch: x64
            name: linux
    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - run: cmake -DCMAKE_BUILD_TYPE=Release -G Ninja
      - run: ninja
      - run: gradle makeJar publish --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          INPUT: "libfabric_installer_native_lib.${{matrix.ext}}"
          NAME: "${{ matrix.name }}-${{ matrix.arch }}"
          FILENAME: "${{ matrix.name }}-${{ matrix.arch }}.${{matrix.ext}}"